In [ ]:

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES
# TO THE CORRECT LOCATION (/kaggle/input) IN YOUR NOTEBOOK,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

import os
import sys
from tempfile import NamedTemporaryFile
from urllib.request import urlopen
from urllib.parse import unquote, urlparse
from urllib.error import HTTPError
from zipfile import ZipFile
import tarfile
import shutil

CHUNK_SIZE = 40960
DATA_SOURCE_MAPPING = 'shakespeare:https%3A%2F%2Fstorage.googleapis.com%2Fkaggle-data-sets%2F5213734%2F8782141%2Fbundle%2Farchive.zip%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com%252F20240719%252Fauto%252Fstorage%252Fgoog4_request%26X-Goog-Date%3D20240719T175129Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3Db4716059e27a7e166319a818ac3e309ac270c7d5c09594b4e02fa51f290951b2beedd1d3ca1a4d66fe4b65020872b830ea6906065ca20144563307fd3e86181e38c4c8170444dc8ed15bf07cd1f6786872d8b9f5b64bc9543aec39035c01b37c5e4abba64d514ee03ae5ad369f2a017ef368bcc08338250a1f594728683ded838a4b69217cac0290a41ad94a728a56a157b834c73a8782f1b34cafae84f71e1a83072ce354ebfb5d18871678587139c2851fdbbf3fe080b8c7d8fbdba600ccd04b5c41122c4b117cc7a4946801ac89842d66517233d39a43998e452db06385941f24e21abf42e6b1a1b96bc69b40dfdc58ea8cf1455102725b66af157b12349a'

KAGGLE_INPUT_PATH='/kaggle/input'
KAGGLE_WORKING_PATH='/kaggle/working'
KAGGLE_SYMLINK='kaggle'

!umount /kaggle/input/ 2> /dev/null
shutil.rmtree('/kaggle/input', ignore_errors=True)
os.makedirs(KAGGLE_INPUT_PATH, 0o777, exist_ok=True)
os.makedirs(KAGGLE_WORKING_PATH, 0o777, exist_ok=True)

try:
  os.symlink(KAGGLE_INPUT_PATH, os.path.join("..", 'input'), target_is_directory=True)
except FileExistsError:
  pass
try:
  os.symlink(KAGGLE_WORKING_PATH, os.path.join("..", 'working'), target_is_directory=True)
except FileExistsError:
  pass

for data_source_mapping in DATA_SOURCE_MAPPING.split(','):
    directory, download_url_encoded = data_source_mapping.split(':')
    download_url = unquote(download_url_encoded)
    filename = urlparse(download_url).path
    destination_path = os.path.join(KAGGLE_INPUT_PATH, directory)
    try:
        with urlopen(download_url) as fileres, NamedTemporaryFile() as tfile:
            total_length = fileres.headers['content-length']
            print(f'Downloading {directory}, {total_length} bytes compressed')
            dl = 0
            data = fileres.read(CHUNK_SIZE)
            while len(data) > 0:
                dl += len(data)
                tfile.write(data)
                done = int(50 * dl / int(total_length))
                sys.stdout.write(f"\r[{'=' * done}{' ' * (50-done)}] {dl} bytes downloaded")
                sys.stdout.flush()
                data = fileres.read(CHUNK_SIZE)
            if filename.endswith('.zip'):
              with ZipFile(tfile) as zfile:
                zfile.extractall(destination_path)
            else:
              with tarfile.open(tfile.name) as tarfile:
                tarfile.extractall(destination_path)
            print(f'\nDownloaded and uncompressed: {directory}')
    except HTTPError as e:
        print(f'Failed to load (likely expired) {download_url} to path {destination_path}')
        continue
    except OSError as e:
        print(f'Failed to load {download_url} to path {destination_path}')
        continue

print('Data source import complete.')


[==================================================] 6849462 bytes downloaded
Downloaded and uncompressed: shakespeare
Data source import complete.


# Make sure you don't use overlapping sequences as this can lead to overfitting.

ZA Scheduler:
stepuj ga svako malo, ne kao u tutorijalu.
Testiraj prvo malo lambda_LR

In [ ]:
#import numpy as np # linear algebra
from math import sqrt
import torch.nn as nn
import torch.nn.functional as F
from torch import tensor, full, save as torchsave, load as torchload, cuda, int as torchint, zeros
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer
#upali internet
toker = AutoTokenizer.from_pretrained("openai-community/gpt2")
nice = toker("<|endoftext|>")
#videcemo posle sta nam jos treba

# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]


*Za resenje pogledaj greedy decode funkciju. Ima nesto out[:,-1]
Imamo i BLANK_WORD = "\<blank\>". Pogledaj src i tgt sta su, deluje korisno.*
*set_default_device*
# SAMO RUNUJ KOD sa githuba.
removuj iz linuxa prvo pa u D. valjda ce da radi...

*In my case the issue appeared to be that the dtype of the initial hidden state was a double and the input was a float. I don’t quite understand why that is an issue, but casting the hidden state to a float solved the issue. If you have any intuition about why this might be a problem for PyTorch, do let me know in the comments.*

#LABEL SMOOTHING TI FALI

# PAZI! layer norm treba jednom posle MHA i jednom posle FF

In [ ]:
gpu = torch.device('cuda')
TRAIN_INPUT = '/kaggle/input/shakespeare/encoded_train_file.pkl'
TEST_INPUT = '/kaggle/input/shakespeare/encoded_test_file.pkl'
MAX_CONTEXT = 99
MIN_CONTEXT=19
NO_TEST_STRINGS=1000

In [ ]:
#slobodno run-uj

EOF = toker("<|endoftext|>")['input_ids'][0]
NONE = 0
vocab_size = 50257
d=512 #dimenzija
dk = 64
heads = 8
sqrtd = float(sqrt(d))
lr=2e-6
POS_DROPOUT=0.1
NN_DROPOUT=0.1
warmup = 1000

#Very important u annotated transformer je ovaj scheduling. Stavi to cim nesto istrenita.

trainpath = '/kaggle/input/shakespeare/train.txt' #train data
ENC_INPUT = '/kaggle/input/shakespeare/encoded_file.pkl'
ENC_OUTPUT = '/kaggle/working/encoded_file.pkl'
N_TOKENS = 1689337
def tokenize():
    raise Exception("already done")
    max_context = N_TOKENS+10
    curr_context = 0
    reached_lim = False
    context = full((max_context,), EOF, dtype=torchint, device=gpu)
    with open(trainpath,'r') as f:
        for line in f:
            new_ids = toker(line)['input_ids']
            new_len = len(new_ids)
            if(curr_context+new_len>max_context):
                reached_lim=True
            if reached_lim: break
            context[curr_context:curr_context+new_len]=tensor(new_ids)
            curr_context+=new_len
        torchsave(context, ENC_OUTPUT)
        # print(curr_context)
#     inp = F.one_hot(context, vocab_size)
#     print(f'{inp.shape=}')


In [ ]:

mask= torch.arange(0,120,1).view(1,120).expand(120,120) - torch.arange(0,120,1).view(120,1).expand(120,120) > 0
class Tf(nn.Module):
    def __init__(self):
        super().__init__()
        self.embedder = nn.Linear(vocab_size, d,bias=False, device=gpu)
        self.dembedder = nn.Linear(d, vocab_size, bias=False, device=gpu)
        self.dembedder.weight = nn.Parameter(self.embedder.weight.t())
        self.layer_norm = nn.LayerNorm((d,), device=gpu)
        self.pos_dropout = nn.Dropout(POS_DROPOUT)
        self.nn_dropout = nn.Dropout(NN_DROPOUT)
        self.N=6

        self.feedforwards = nn.ModuleList([nn.Sequential(nn.Linear(d,4*d, device=gpu), nn.ReLU(), nn.Linear(4*d,d, device=gpu), nn.ReLU())
                       for _ in range(self.N)])
        self.queries = nn.ModuleList([nn.Linear(d,heads*dk,device=gpu) for _ in range(self.N)])
        self.keys = nn.ModuleList([nn.Linear(d,heads*dk,device=gpu) for _ in range(self.N)])
        self.values = nn.ModuleList([nn.Linear(d,heads*dk,device=gpu) for _ in range(self.N)])
        self.qksoftmax = nn.Softmax(-1)
        #Q=Qnn @ Hi=[len, heads, dk]. Q[i] je MH query.
        #
        #Qnn =  [heads,dk]
        # mozda::::::Qnn in=d, out=heads*dk
        #K = Knn*H = [len,heads,dk]
        #QK = Q dot K (kako?) = [len,len,heads]
        #Naime QK[i] = matrica proporcije za i-ti element.
        #QK[i]=sumj(Q[i] dot-po-dk K[j]) OVO NE ZVUCI TACNO
        #QK[i,j]=sumx(Q[i,:,x]*K[j,:,x]). Nadam se da ovde lepo radi broadcasting

        # H L D, H D L -> H L L moze. Koristi .transpose(dim0, dim1) da bi sredio ovo.

        #V=Vnn*H = [len,heads,dk]
        #MHO = [len, heads, dk]
        #MHO[i,h] = sumj(QK[i,j,h]*V[j,h])
        #MHO = QK(T!) dot VT
        #QKT = [h,l,l]; VT = [h,l,d]
        #O = [len, d] = MHO.squeeze(1,0) #uradi ovo sa view
        #H = [len,d]
        #Hi = [len,d,1]
        #Kako se inace oznacavaju neuralne sa matricnim mnozenjem.......
        #Mi zavrsimo sa jednim sequencom emb O[len,d]. O[i] = sum()
    def add_pos_embedding(self, a, predict_pos):
        #print(f'{a.abs().mean()=}')

        lin = torch.arange(0,a.shape[-2]/10000,1/10000,device=gpu).unsqueeze(1).to(gpu).expand(a.shape[-2],d)
        pows = torch.arange(0,1,1/d).unsqueeze(0).to(gpu).expand(a.shape[-2],d)#.expand(-1, a.shape[-1]).to(gpu)
        pows = torch.pow(lin, pows)
        fin = torch.sin(pows)
        fin[::2] = torch.cos(pows)[::2]
        #print(f'{fin.requires_grad=}')
        a=a+(fin)
        #print(f'{fin.abs().mean()=}')
        return self.pos_dropout(a.float())




    #treba i za ovo dropout...


    def mha(self,vnnres,knnres,qnnres, d, dk, heads):
        # print(f'{knnres.shape=}')
        # print(f'{vnnres.shape=}')
        # print(f'{qnnres.shape=}')
        l = knnres.shape[-2]
        assert(d==dk*heads)
        v = vnnres.view(l,heads,dk).transpose(-2,-3)
        #print(f'{v=}')
        q = qnnres.view(l,heads,dk)
        #print(f'{q=}')
        k = knnres.view(l,heads,dk)
        #print(f'{k=}')
        k = k.transpose(-3,-2).transpose(-2,-1)
        #print(f'{k=}')
        q = q.transpose(-3,-2)
        #print(f'{q=}')
        qk = torch.matmul(q,k)
        #print(f'{qk=}')
        qk = qk / float(sqrt(dk))
        qk[:,mask[:l,:l]] = float('-inf')
        #print(f'{qk=}')
        qk = self.qksoftmax(qk)
        #print(f'{qk=}')
        o = torch.matmul(qk,v)
        #print(f'{o=}')
        o = o.transpose(-3,-2).reshape((1,l,d)) #ovde je bilo (bat,l,d)
        #print(f'{o=}')
        return o
    def testmha(self):
      #probaj s manjim dimenzijama, stavi neki if za testiranje
        l = 5
        d = 6
        dk=3
        heads=2
        vnnres = (torch.rand((l,d),device=gpu)*5).int().float()
        knnres = (torch.rand((l,d),device=gpu)*5).int().float()
        qnnres = (torch.rand((l,d),device=gpu)*5).int().float()
        print(f'{vnnres=}')
        print(f'{knnres=}')
        print(f'{qnnres=}')
        self.mha(vnnres,knnres,qnnres,d,dk,heads)
    def attentionstack(self,h):
        for i in range(self.N):
            q = self.queries[i](h)
            k = self.keys[i](h)
            v = self.values[i](h)
            h = self.mha(v,k,q,d,dk,heads)
            h = self.layer_norm(h+self.nn_dropout(self.feedforwards[i](h)))
        return h

    def forward(self, h):
#         h[:-1] = encoded_input #realno ga kopira
        predict_pos = h.shape[-1]-1
        #print(f'{h=} pre one_hot')
        h = F.one_hot(h, vocab_size).float()
        #print(f'{h.requires_grad=} {h.device=}  nakon one_hot')
        h = (self.embedder(h)*sqrtd).float()
        #Ovde krene requires_grad=True. Ppvljam zato sto je ovaj grad bitan za embedder a ostalo nije bitno.
        #print(f'{h.requires_grad=} {h.device=}  nakon embedder')
        h = self.add_pos_embedding(h, predict_pos)

        #ovde neko matricno mnozenje da bi konacno interagovale stvari
        #jao cekaj treba multi sranje. A kako je annotated napravio liste jbm ga
        #samo procitaj rad molim te ima nekih korenova



        #print(f'{h.requires_grad=} nakon pos emb')


        h = self.attentionstack(h) #ne moramo jos...


        #print(f'{h.shape=} nakon attlayers')
        h = self.dembedder(h[:,predict_pos])
        #print(f'{h.requires_grad=} nakon dembedder')
        #uradi dropout
        return h

## Procitaj sta je layer normalization

### MISLIM DA MOZE SVE DA BUDE H. Pitaj nekoga kako to.
Rekao bih da += ne pravi kopiju u memoriji koja se cuva za graf, a a=a+x ili a= self.conv(a) radi to. Medjutim zasto to u forumu nije ponudjeno kao laki fiks?

### Nadji mesto gde decoder smanjuje dimenziju tenzora

### Sta ako on dobije sequence "Ja idem u \_" i onda tu donju-crtu pretvori u nesto? I onda pogleda samo taj token na kraju.

Od kog tokena se krece? Sve nule u embedingu?

## Dodaj learning rate majke ti
## Sta je loss.item(). Nigde nisu sumovali nista

## Bezi bre zasto nisam za test_input stavio jos +max context ?

In [ ]:

def train_test_split():
    raise Exception("already done")
    t = torchload(ENC_INPUT)
    torchsave(t[:-(MAX_CONTEXT+NO_TEST_STRINGS)].clone(),TRAIN_INPUT)
    torchsave(t[-(MAX_CONTEXT+NO_TEST_STRINGS):].clone(), TEST_INPUT)

Why linear tako jadno

In [ ]:


class VerseDataset(Dataset):
    def __init__(self, einput):
        super().__init__()
        self.t = torchload(einput)
        self.rnd_modifier = 0
    def __getitem__(self,i):
        i+=MAX_CONTEXT+1
        conlen = (((i+self.rnd_modifier)%5)+1)*20-1

        h = (self.t[i-conlen:i]).long()#,device=gpu,dtype=torch.float32, requires_grad=True
        return (h, (self.t[i]).long())

class TrainDataset(VerseDataset):
    def __init__(self):
        super().__init__(TRAIN_INPUT)
    def __len__(self):
        return N_TOKENS - 1 - MAX_CONTEXT - NO_TEST_STRINGS
class TestDataset(VerseDataset):
    def __init__(self):
        super().__init__(TEST_INPUT)
    def __len__(self):
        return NO_TEST_STRINGS - 1

trainDataset = TrainDataset()
testDataset = TestDataset()
trainLoader = DataLoader(trainDataset, shuffle=True)
testLoader = DataLoader(testDataset, shuffle=True)
verseIter = iter(trainLoader)
#print(verseIter[0])

model = Tf()
for p in model.parameters():
    if p.dim() > 1:
        nn.init.xavier_uniform_(p)


iterparam = model.named_parameters()
criterion = nn.CrossEntropyLoss()
def print_parameters():
    try:
        while True:
            print(f'{next(iterparam)=}')
    except Exception:
        pass

#optimizer = torch.optim.Adam(model.parameters(), lr=lr, betas=(0.9, 0.98), eps=1e-9)
def rate(step, model_size, factor, warmup):

    if step == 0:
        step = 1
    return factor * (
        model_size ** (-0.5) * min(step ** (-0.5), step * warmup ** (-1.5))
    )


optimizer = torch.optim.Adam(
        model.parameters(), lr=1, betas=(0.9, 0.98), eps=1e-9
    )
lr_scheduler = torch.optim.lr_scheduler.LambdaLR(
    optimizer=optimizer,
    lr_lambda=lambda step: rate(
        step, d, factor=1, warmup=warmup
    ),
)

train_loss_dic={}
NO_EPOCHS=6
NO_BATCHES=100

In [ ]:
model.testmha()

vnnres=tensor([[3., 2., 4., 3., 3., 0.],
        [0., 3., 4., 0., 3., 3.],
        [0., 0., 2., 0., 2., 3.],
        [1., 3., 4., 2., 0., 4.],
        [3., 0., 3., 0., 1., 2.]], device='cuda:0')
knnres=tensor([[3., 3., 0., 2., 0., 3.],
        [0., 4., 2., 4., 4., 3.],
        [3., 3., 3., 2., 1., 4.],
        [0., 0., 3., 1., 0., 2.],
        [4., 2., 4., 1., 1., 3.]], device='cuda:0')
qnnres=tensor([[1., 2., 4., 2., 4., 4.],
        [2., 2., 2., 1., 2., 3.],
        [0., 2., 0., 1., 4., 1.],
        [3., 4., 0., 2., 2., 4.],
        [1., 3., 3., 1., 0., 3.]], device='cuda:0')


### Pazi! Ono sto dobijes na kraju nije softmaxovano

In [ ]:

testIter = iter(testLoader)
string_preds = []
token_preds={}
logit_preds = []
NUM_OF_DIFF_TESTS = NO_EPOCHS #vrati na 1 kad zavrsis
def test():
    test_loss=0
    with torch.no_grad():
        for i in range((NO_TEST_STRINGS-1)//NUM_OF_DIFF_TESTS):
            input_string, label = next(testIter)
            label = label.long()
            #label = F.one_hot(label, vocab_size).float() #ovo je safe za mapu
            #print(f'{label.dtype=} {label=}')
            baby = model(input_string)
            #treba baby[0] uvek
            loss = criterion(input=baby,target=label)
            test_loss+=loss.sum() #msm da ovo ne treba ovk
            #print(f'{input_string.shape=} {baby[0].argmax().shape=}')
            pred_num = baby[0].argmax()
            pred_word = toker.decode(pred_num)
            string_preds.append(toker.decode(torch.cat((input_string.squeeze(),pred_num.unsqueeze(0)))))
            token_preds[pred_word] = token_preds.get(pred_word,0)+1
            logit_preds.append(baby[0])
#test()

In [ ]:
l = [0]*70000
for i,(inp,label) in enumerate(trainLoader):
  print(inp)
  print(label)
  if i==10: break

tensor([[  198,   198, 16219,  8267,  1546,    13,   198,    40,   447,   247,
           297,  4894,   465,  2910,   351,  8312,   680,  8237,  9975,    11,
           198, 13828,   351,   616,   629,   320,  7940,   314,   447,   247,
           297,  3608,  9439,    13,   198, 12130,   305,  2527,    11,  1309,
           514, 26951,   683,   284,   262,  6001,    13,   198,   198,    47,
          1404,    49,  4503,    43,  2937,    13,   198,  4342,  2058,   309,
          7084,  2737,    13,   198,   198,  6062,   309,  7084,  2737,    13,
           198,   198, 16219,  8267,  1546,    13,   198,  2437,   783]],
       device='cuda:0')
tensor([11], device='cuda:0')
tensor([[  717,  1570,  2236,  1494,   198,  3237, 29693,    13,  3914,   683,
           407,  1265,   674, 27322,    26,   198,   464,  3450,   286,   465,
          1049, 14148,   318,  2636,    11,   198,  1870,  9211,   621,   909,
         26018,   466,   356, 30033,   198,   817,   447,   247,   753, 26426,
   

In [ ]:
def train():
    global token_preds
    for epoch in range(NO_EPOCHS):
        epoch_loss=0
        test()
        # print(f'{model.dembedder.weight[0].mean()=}')
        # print(f'{model.dembedder.weight[1].mean()=}')
        # print(f'{model.dembedder.weight[2].mean()=}')
        # print(f'{model.dembedder.weight[3000].mean()=}')

        #for s in string_preds[:10]: print(s, '\nEND')

        for logit in logit_preds[:10]: print(f'{logit=}')

        for q in list(token_preds.items()):
            print(q)
        token_preds={}

        for i in range(NO_BATCHES):
            input_string, label = next(verseIter)
            label = label.long()
            #label = F.one_hot(label, vocab_size).float() #ovo je safe za mapu
            #print(f'{label.dtype=} {label=}')
            #print(f'{input_string=}')
            baby = model(input_string)
            #print(f'{baby.argmax()=}')
            #print(f'{toker.decode(baby.argmax())=}')
            #print(f'{baby-label=}')
            loss = criterion(input=baby,target=label)
            epoch_loss+=loss.sum()
            loss.backward()
            if i==100:
                # for par in model.named_parameters():
                #     print(f'{par=}')
                #     print(f'{par[1].grad=}')
                print(f'{model.dembedder.weight.grad[0:10]=}')
            optimizer.step()
            optimizer.zero_grad()
        train_loss_dic[epoch]=epoch_loss





train()

model.dembedder.weight[0].mean()=tensor(-0.0003, device='cuda:0', grad_fn=<MeanBackward0>)
model.dembedder.weight[1].mean()=tensor(-0.0004, device='cuda:0', grad_fn=<MeanBackward0>)
model.dembedder.weight[2].mean()=tensor(-0.0003, device='cuda:0', grad_fn=<MeanBackward0>)
model.dembedder.weight[3000].mean()=tensor(0.0002, device='cuda:0', grad_fn=<MeanBackward0>)
tensor([ 0.1779,  0.2084, -0.1492,  ...,  0.0315, -0.0774,  0.1893],
       device='cuda:0')
tensor([ 0.1238,  0.0836, -0.0761,  ...,  0.0898, -0.0833,  0.2051],
       device='cuda:0')
tensor([ 0.1988,  0.2359, -0.1065,  ...,  0.0775,  0.0340,  0.2440],
       device='cuda:0')
tensor([ 0.1381,  0.0750, -0.1432,  ...,  0.0638, -0.1691,  0.1462],
       device='cuda:0')
tensor([ 0.1617,  0.1596, -0.1482,  ...,  0.0996, -0.1174,  0.1291],
       device='cuda:0')
tensor([ 0.1847,  0.1407, -0.1334,  ...,  0.1320, -0.0660,  0.2130],
       device='cuda:0')
tensor([ 0.1565,  0.1634, -0.1359,  ...,  0.0019, -0.1011,  0.1800],
       

Uglavnom konvergira ka \n ili ka ,

Ups - dobio sam index error  za neki dataset. IndexError: index 1688259 is out of bounds for dimension 0 with size 1688249

In [ ]:
print(train_loss_dic)

{0: tensor(1075.4215, device='cuda:0', grad_fn=<AddBackward0>), 1: tensor(1064.2625, device='cuda:0', grad_fn=<AddBackward0>), 2: tensor(1060.9318, device='cuda:0', grad_fn=<AddBackward0>), 3: tensor(1047.1924, device='cuda:0', grad_fn=<AddBackward0>), 4: tensor(1040.4023, device='cuda:0', grad_fn=<AddBackward0>), 5: tensor(1030.9938, device='cuda:0', grad_fn=<AddBackward0>)}


12 JUL: svugde stavlja uzvicnik. vrv se necega nisam setio da uradim lol

## Moras svugde da ubacis batches cim vidis da radi.